---
title: "HW_2Week3"
author: "Rivka Schuster"
date: "June 27, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

library(glmnet)
getPowerOne <- function(n, d, M=100, alpha = .05){

  isClose <- rep(0, M)
 
  
  for(i in 1:M){
    #print(i)
    
     df <- data.frame(blank = rep(0, n))
 df$errors <- rnorm(n*1)
  df$treated  = (rep(0:1, each = n/2))
    #generate data with real effect
    df$y = d * df$treated+ df$errors
    results  = glm(df$y ~ df$treated)
  dHatValue = summary(results)$coefficients["df$treated", 4]
   if(dHatValue < alpha){
     isClose[i] = 1 #yes it is sinificant
   }
   else{
     isClose[i] = 0 
   }
   
  }
 return (sum(isClose)/M)
  #return proportion of loops where it was significant
  
  
}

run1 <- getPowerOne(1000, .5)
run2 <- getPowerOne(1000, .5, 100, .01)


```


```{r}
#Build a higher-level function that takes d and power = 0.80 that outputs N required. This will call the base function.
getNRequired = function(d, power = .80){
  N=1000 #MAX OUT AT 1000
  for(i in seq(from=2, to=N, by=2)){
     mypower =  getPowerOne(i, d)
     if(mypower == power){
       return(i)
     }
  }

}

nRquired = getNRequired(.5)
```


```{r}
getDRequired = function(n, power = .80){
  
  getPowerOne()
  
}
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
